# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 22:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=models.TextField(default=datetime.datetime(2018, 4, 3, 22, 8, 11, 502431, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
