# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-27 22:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='report_period',
            field=models.DurationField(choices=[(datetime.timedelta(0), 'Disabled'), (datetime.timedelta(1), 'Day'), (datetime.timedelta(7), 'Week'), (datetime.timedelta(30), 'Month')], default=datetime.timedelta(0)),
        ),
    ]
